apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-mem
spec:
  selector:
    matchLabels:
      run: my-python-app
  replicas: 1
  template:
    metadata:
      labels:
        run: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: alef123vinicius/python-app:v1
        ports:
        - containerPort: 19000
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-mem
  labels:
    run: my-python-app
spec:
  ports:
  - port: 5002
  selector:
    run: my-python-app
