- name: Copy file with owner and permissions
  copy:
    src: /home/alef/DESAFIO_NATURA/my-solution/ansible/join/kubejoin.sh
    dest: /tmp/kubejoin.sh
    owner: root
    group: root
    mode: '0700'

- name: run command on remote
  shell: /tmp/kubejoin.sh
