stage('Deploy Patient App') {
    steps {
        withCredentials([ string(credentialsId: 'kubernetes', variable: 'api_token') ]) {
            sh 'kubectl --token $api_token --server https://192.168.99.101:8443 --insecure-skip-tls-verify=true apply -f my-python-app-cpu.yaml '
        }
    }
}

stage('Deploy HPA App conf') {
    steps {
        withCredentials([ string(credentialsId: 'kubernetes', variable: 'api_token') ]) {
            sh 'kubectl --token $api_token --server https://192.168.99.101:8443 --insecure-skip-tls-verify=true apply -f my-python-app-hpa.yaml '
        }
    }
}
