apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      run: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      containers:
      - name: jenkins
        image: alef123vinicius/jenkins:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1Gi
          requests:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    run: jenkins
spec:
  ports:
  - port: 8080
  selector:
    run: jenkins
  type: LoadBalancer
