apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jenkins-cpu
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jenkins
  maxReplicas: 3
  minReplicas: 1
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 70  
